=== bhattavi/XML-parser-project/domParserDTD/employees.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee)+>
<!ELEMENT employee (id,firstName,lastName,income)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT income (#PCDATA)>

=== bhattavi/XML-parser-project/xml, dtd, xsd/dtd, xml/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
	<employee>
		<id>1</id>
		<firstName>John</firstName>
		<lastName>Smith</lastName>
		<income>50000</income>
	</employee>
	<employee>
		<id>2</id>
		<firstName>David</firstName>
		<lastName>Lee</lastName>
		<income>70000</income>
	</employee>
	<employee>
		<id>3</id>
		<firstName>Tom</firstName>
		<lastName>Flowers</lastName>
		<income>40000</income>
	</employee>
	<employee>
		<id>4</id>
		<firstName>Rupert</firstName>
		<lastName>Johnson</lastName>
		<income>80000</income>
	</employee>
	<employee>
		<id>5</id>
		<firstName>Dave</firstName>
		<lastName>Moris</lastName>
		<income>90000</income>
	</employee>
</employees>
